# Generated by Django 4.2.5 on 2023-09-13 04:36

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                (
                    "article_slug",
                    models.SlugField(null=True, unique=True, verbose_name="slug"),
                ),
                ("content", tinymce.models.HTMLField()),
                (
                    "published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date published"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date modified"
                    ),
                ),
            ],
        ),
    ]
