# Generated by Django 4.2.5 on 2023-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author_id",
            field=models.CharField(default="admin"),
        ),
    ]
